version: '3'

services:
  babyheap--:
    build: ./
    volumes:
      - ./share:/home/Babyheap--:ro
      - ./xinetd:/etc/xinetd.d/babyheap--:ro
    ports:
      - "10101:10101"
    expose:
      - "10101"
